### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by raatmarien** [raatmarien/playcardswith.me#10]
Think up a name and create a cool logo.

**Comment by raatmarien** [comment]
Name: PlayCardsWith.Me. Now we just need a logo

**Comment by jchmrt** [comment]
I'm thinking of something like this:

![logo idea](https://lutim.lagout.org/bHg06eFX/tWFS3uAc.png)

So using the text on some cards held like they are in a hand. I'll try to work it out further.

**Comment by raatmarien** [comment]
I think that is a nice idea

**Comment by jchmrt** [comment]
![logo-idea-2-tmp](https://user-images.githubusercontent.com/5506908/78387269-52786480-75df-11ea-89b7-61ebac1ee1af.png)

What do you think of this?

**Comment by raatmarien** [comment]
I like it. I just think there is one too many colors here with the red, white, yellow, blue, green and orange. Maybe join room can be the same color as the cards

**Comment by raatmarien** [comment]
I kind of liked the blue cards as well. Did that not work in the design on the front page?

**Comment by jchmrt** [comment]
I kindof thought more blue looked really boring, because the entire background is already blue...

**Comment by raatmarien** [comment]
Makes sense

**Comment by jchmrt** [comment]
![test](https://user-images.githubusercontent.com/5506908/78388841-011da480-75e2-11ea-86d6-1e0c2d39d462.png)
How about this, more of a casino table vibe with the red background.

**Comment by raatmarien** [comment]
Oh ja, dat is wel mooi!

**Comment by raatmarien** [comment]
Oh that looks nice! I'm only not sure about the New Room button going over the logo so much.

**Comment by raatmarien** [comment]
![https://lutim.lagout.org/HWzzDtAp/bPOk8Osl.png](https://lutim.lagout.org/HWzzDtAp/bPOk8Osl.png)

What about a spacing like this? Apart from the colors.

**Comment by raatmarien** [comment]
![https://lutim.lagout.org/hVRbkhss/MhJk677T.png](https://lutim.lagout.org/hVRbkhss/MhJk677T.png)

Or without the cursor?

**Comment by raatmarien** [comment]
![https://lutim.lagout.org/fBCc7N7P/zwR8liil.png](https://lutim.lagout.org/fBCc7N7P/zwR8liil.png)

**Comment by jchmrt** [comment]
So this is with that kind of spacing:

![image](https://user-images.githubusercontent.com/5506908/78391306-68d5ee80-75e6-11ea-8e5c-8dd2facf71ad.png)

**Comment by jchmrt** [comment]
And this is with shorter spacing:

![image](https://user-images.githubusercontent.com/5506908/78391357-80ad7280-75e6-11ea-8f47-a233ce7d2fe7.png)

**Comment by jchmrt** [comment]
I think I prefer it with the overlap, to be honest

**Comment by jchmrt** [comment]
I think the pixelated cursor looks a bit jarring, with all other things being smooth

**Comment by flori9** [comment]
Wow that looks great! I like the version with overlap more.

Very minor: maybe the . in .me should be a bit more visible so people know it's an URL? Just moving that card to the right slightly would do that.

**Comment by jchmrt** [comment]
Good point! I don't want to have the '.' completely in view, because then it kindof looks odd since all other words are cut off on the side. But here I have given the '.' a bit more space:

![image](https://user-images.githubusercontent.com/5506908/78398780-f66c0b00-75f3-11ea-9fcc-dd0d92b2ca4a.png)

What do you think @flori9 ?

**Comment by flori9** [comment]
I get that; I think it's great like this!

**Comment by raatmarien** [comment]
Nice. It is probably better with this new favicon to also use it in the header, like this:

![https://lutim.lagout.org/UdDUaoxQ/XREhOxd8.png](https://lutim.lagout.org/UdDUaoxQ/XREhOxd8.png)
