### ISSUE TITLE
action on user leave room 

### ISSUE THREAD

**Issue by sambeard** [raatmarien/playcardswith.me#136]
What should happen to the hand  of a player when he/ she leaves the room?
At the moment the cards in the hand just 'disappear'. Possibly move cards to the sink, as mentioned in issue #129 . Other option if to place card back in the deck or just on the table. Maybe we should make this configurable.

Other thing that should be added is a pop up 'Are you sure you want to leave (you will lose your current hand)'

**Comment by jchmrt** [comment]
I think at least for now (as we don't have a sink yet) we should implement that the cards go back to the deck or the table, so that you can't completely lose cards if someone leaves.
