### ISSUE TITLE
Show info from other players

### ISSUE THREAD

**Issue by flori9** [raatmarien/playcardswith.me#77]
For example on the top of the screen. The following info could be useful:

- [x] Name
- [x] Color
- [x] Number of cards in their hand

**Comment by raatmarien** [comment]
I think the name and color will be nice in the header (colored name).

**Comment by raatmarien** [comment]
Although when we add the other player decks to show how many cards they have I also want to be able to drag cards to other players decks, so that is a bit more work. As soon as we do that though, the player names and colors can be taken out of the header and just moved to the corresponding deck.

**Comment by raatmarien** [comment]
Or maybe it is better to just start with showing the decks on the side and not allow us to drag their yet.

**Comment by raatmarien** [comment]
Basic UI is done in this PR
