### ISSUE TITLE
"Player requested to release without dragging: <player-id>"

### ISSUE THREAD

**Issue by jchmrt** [raatmarien/playcardswith.me#98]
These messages show up somewhat frequently in production, normally they are clustered in 2-5 repetitions of the message with the same player id. I'm not sure why it happens or if it is a problem, but we should investigate it and disable the message if it is not a problem.

**Comment by flori9** [comment]
This happens when people click on the deck to get a card. In that case, onDragStop happens without a preceding onDragMove.
The best way to resolve this would probably be to make pick_from_deck instantly start dragging the card on the server side.
I'll assign myself and try to resolve this.
